name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - name: Upload kcomp exec
      uses: actions/upload-artifact@v4.3.3
      with:
        name: kcomp
        path: kcomp
